projects:
  app:
    schemaPath: apollo-server/schema.graphql
    includes:
      - 'apollo-server/**/*.graphql'
      - 'apollo-server/**/*.gql'
    extensions:
      endpoints:
        default: 'http://localhost:4000/graphql'
