version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "4000:4000"
  #   links:
  #     - postgres
  # postgres:
  #   image: postgres:10-alpine
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: codinschool
volumes:
  postgres: {}
