version: '3'
services:

  # DEVELOPPEMENT

  web:
    build: .
    ports:
      - "4000:4000"

  # PRODUCTION

  # web:
  #   build: .
  #   ports:
  #     - "80:80"
  #   environment:
  #     NODE_ENV: "production"
  #     SECRET_JWT: "modeDeveloppement"

  #   links:
  #     - postgres
  # postgres:
  #   image: postgres:10-alpine
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: codinschool
# volumes:
  # postgres: {}
