fragment utilisateur on Profile {
  id
  nom
  prenom
  emailPrimaire
  dateInscription
  roles {
    id
    nom
  }
  permissions
  dateNaissance
  adresse
  codePostal
  emailSecondaire
  telephonePrimaire
  telephoneSecondaire
  diplome
  anneeDiplome
  siteWeb
  avatar
}
