fragment utilisateur on Profile {
  id
  nom
  prenom
  emailPrimaire
  dateInscription
  role
  dateNaissance
  adresse
  codePostal
  emailSecondaire
  telephonePrimaire
  telephoneSecondaire
  diplome
  anneeDiplome
  siteWeb
  avatar
}
