query RecupererProfil {
  moi {
    pseudo
    permissions
    profile {
      id
      incritDepuis
      roles {nom}
      nom
      prenom
      dateNaissance
      adresse
      codePostal
      emailPrimaire
      emailSecondaire
      telephonePrimaire
      telephoneSecondaire
      diplome
      anneeDiplome
      siteWeb
      avatar
    }
  }
}
