#import "./FragmentTest.gql"
#import "./FragmentExercice.gql"
#import "./FragmentNiveau.gql"

mutation EditerTest($id: ID!, $modifications: EditionTest!) {
  editerTest(id: $id, modifications: $modifications) {
    ...test
    exercice {
      ...exercice
      niveau {
      ...niveau
      }
    }
  }
}