query Soumissions {
  soumissions {
    code
    compilation {
      code
      duree
      reussie
      stderr
      stdout
    }
    date
    duree
    exercice {
      id
      titre
    }
    id
    nbPasses
    nbTests
    resultats {
      attendu
      duree
      entree
      id
      nom
      passe
      stderr
      stdout
    }
  }
}
