#import "./FragmentTest.gql"
#import "./FragmentExercice.gql"
#import "./FragmentNiveau.gql"

query Test($id: ID!) {
  test(id: $id) {
    ...test
    exercice {
      ...exercice
      niveau {
        ...niveau
      }
    }
  }
}
